spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: GreenPulse
    password:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml
  server:
    port: 8081
