spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: GreenPulse
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create